<?php

/**
 * @file
 * Provides Simple Node archive style options for Views.
 */

/**
 * Implements hook_views_api().
 */
function sna_blocks_views_api() {
  return array(
    'api' => '3',
    'path' => drupal_get_path('module', 'sna_blocks'),
  );
}

/**
 * Need to have preprocess functions here because drupal doesn't cache them
 * correctly in the theme.inc file.
 */

// Trying to make sure the theme.inc get's loaded.
include_once 'theme/sna_blocks.theme.inc';

function template_preprocess_sna_blocks(&$vars) {
  _sna_blocks_preprocess_sna_blocks($vars);
}
